services:
  jekyll:
    build: 
      context: .
      dockerfile_inline: |
        FROM jekyll/jekyll:3.8.6
        RUN gem update --system 3.3.22
    image: github-jekyll
    volumes:
      - ./docs:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle

  jekyll-serve:
    extends: jekyll
    command: ["jekyll", "serve", "--watch", "--livereload"]
    ports:
      - ${JEKYLL_PORT:-4000}:4000