# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Marco Luzzara
title_separator: "-"
email: marco.luzzara.work@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A developer who loves to automate things
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marco-luzzara.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  marco-luzzara
repository: "marco-luzzara/marco-luzzara.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
encoding: "utf-8"

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# ***********************************************
# Theme configurations
# ***********************************************

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

locale: "en-US"
include: ["_pages"]

defaults:
  # _posts
  - scope:
      path: ""
      type: posts 
    values:
      layout: single
      read_time: true
      show_date: true
      comments: true
      share: true
      related: true
      toc: true
      permalink: "/:categories/:title/"
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      toc: true

author:
  name     : "Marco Luzzara"
  avatar   : "/assets/images/bio.jpg"
  bio      : "A developer who loves to automate things."
  location : "Mantova, Italy"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:marco.luzzara.work@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/marco-luzzara"
    - label: "StackOverflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/5587393/marco-luzzara"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/marco-luzzara"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:marco.luzzara.work@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/marco-luzzara"
    - label: "StackOverflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/5587393/marco-luzzara"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/marco-luzzara"

paginate: 10
paginate_path: "/articles/page:num/"

comments:
  provider: "giscus"
  giscus:
    repo_id              : "R_kgDOMMgtbA" # Shown during giscus setup at https://giscus.app
    category_name        : "Announcements" # Full text name of the category
    category_id          : "DIC_kwDOMMgtbM4Cwrxq" # Shown during giscus setup at https://giscus.app
    discussion_term      : "pathname" # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : "1" # '1' for enabled (default), '0' for disabled
    theme                : "preferred_color_scheme" # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"

# <script src="https://giscus.app/client.js"
#         data-repo="marco-luzzara/marco-luzzara.github.io"
#         data-repo-id="R_kgDOMMgtbA"
#         data-category="Announcements"
#         data-category-id="DIC_kwDOMMgtbM4Cwrxq"
#         data-mapping="pathname"
#         data-strict="0"
#         data-reactions-enabled="1"
#         data-emit-metadata="0"
#         data-input-position="top"
#         data-theme="preferred_color_scheme"
#         data-lang="en"
#         data-loading="lazy"
#         crossorigin="anonymous"
#         async>
# </script>

enable_copy_code_button: true

category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    # year: '/:year/'
    # month: '/:year/:month/'
    # day: '/:year/:month/:day/'
    tag: '/tags/:name/'
    category: '/categories/:name/'
breadcrumbs: true

search: true
lunr:
  search_within_pages: true